"""Adicionado Produto, Categoria e Relacionamentos

Revision ID: ed9743664e9c
Revises: 
Create Date: 2022-01-09 17:28:04.034766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed9743664e9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('categoria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('idCategoria', sa.INTEGER(), server_default=sa.text('nextval(\'"categoria_idCategoria_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idCategoria', name='categoria_pkey'),
    sa.UniqueConstraint('tipo', name='categoria_tipo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('produto',
    sa.Column('idProduto', sa.INTEGER(), server_default=sa.text('nextval(\'"produto_idProduto_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('valor', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('desconto', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tamanho', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ingredientes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idCategoria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('imagem_1', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('imagem_2', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('imagem_3', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categoria.idCategoria'], name='produto_idCategoria_fkey'),
    sa.PrimaryKeyConstraint('idProduto', name='produto_pkey')
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('profile', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    sa.UniqueConstraint('email', name='usuario_email_key'),
    sa.UniqueConstraint('nome', name='usuario_nome_key')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('funcao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('foto', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key')
    )
    # ### end Alembic commands ###
